precise-default:
  product: compute
  name: default
  os: precise
  os-features:
    glance:
      - cf
    cinder:
      - local
  nodes:
    - [chefserver]
    - [controller, cinderlocal]
    - [compute]

centos-default:
  product: compute
  name: default
  os: centos
  features:
    - glancecf
    - cinderlocal
  nodes:
    - [chefserver]
    - [controller, cinderlocal]
    - [compute]

precise-ha:
  product: compute
  name: ha
  os: precise
  os-features:
    glance:
      - cf
  rpcs-features:
    - ha
  nodes:
    - [chefserver]
    - [controller]
    - [controller]
    - [compute]

centos-ha:
  product: compute
  name: ha
  os: centos
  features:
    glance:
      -cf
    - ha
  nodes:
    - [chefserver]
    - [controller]
    - [controller]
    - [compute]

precise-openldap:
  product: compute
  name: openldap
  os: precise
  features:
    - openldap
  nodes:
    - [directory-server]
    - [chefserver]
    - [controller]
    - [compute]

centos-openldap:
  product: compute
  name: openldap
  os: centos
  features:
    - openldap
  nodes:
    - [directory-server]
    - [chefserver]
    - [controller]
    - [compute]

precise-swift:
  product: compute
  name: swift
  os: precise
  features:
    - swift
  nodes:
    - [chef-server]
    - [controller]
    - [proxy1]
    - [proxy2]
    - [storage1]
    - [storage2]
    - [storage3]

centos-swift:
  product: compute
  name: swift
  os: centos
  features:
    - swift
  nodes:
    - [chefserver]
    - [controller]
    - [proxy1]
    - [proxy2]
    - [storage1]
    - [storage2]
    - [storage3]

precise-neutron:
  product: compute
  name: neutron
  os: precise
  features:
    - neutron
    - ha
  nodes:
    - [chefserver]
    - [controller, neutron]
    - [controller, neutron]
    - [compute]

centos-neutron:
  product: compute
  name: neutron
  os: centos
  features:
    - neutron
    - ha
  nodes:
    - [chefserver]
    - [controller, neutron]
    - [controller, neutron]
    - [compute]