chef:
  server: 
    install_script: https://raw.github.com/rcbops/jenkins-build/master/qa/bash/jenkins/install-chef-server.sh

razor:
  ip: 198.101.133.3

rcbops:
    compute:
        git:
            url: https://github.com/rcbops/chef-cookbooks.git
            branches:
                havana:
                    tags:
                        - v4.2.0
                grizzly:
                    tags:
                        - v4.1.2
                        - v4.1.1
                        - v4.1.0
                        - v4.0.0
                folsom:
                    tags:
                        - v3.0.0
                        - v3.0.1
                        - v3.1.0
        chef_server:
            run_list: []
        compute:
            run_list: ['role[single-compute]']
        directory_server:
            run_list: ['role[qa-openldap]']
        controller1:
            run_list: ['role[ha-controller1]', 'role[cinder-all]']
        controller2:
            run_list: ['role[ha-controller2]']

environments:
    ha:
        vips:
            mysql-db: "198.101.133.154"
            rabbitmq-queue: "198.101.133.155"
            cinder-api: "198.101.133.156"
            glance-api: "198.101.133.156"
            glance-registry: "198.101.133.156"
            horizon-dash: "198.101.133.156"
            horizon-dash_ssl: "198.101.133.156"
            keystone-admin-api: "198.101.133.156"
            keystone-internal-api: "198.101.133.156"
            keystone-service-api: "198.101.133.156"
            nova-api: "198.101.133.156"
            nova-ec2-public: "198.101.133.156"
            nova-novnc-proxy: "198.101.133.156"
            nova-xvpvnc-proxy: "198.101.133.156"
            swift-proxy: "198.101.133.156"
            config:
                198.101.133.154:
                    vrid: 10
                    network: "public"
                198.101.133.155:
                    vrid: 11
                    network: "public"
                198.101.133.156:
                    vrid: 12
                    network: "public"
    neutron:
        nova:
            network:
                provider: "quantum"
                apply_patches: True
    storage:
        git:
            url: "https://github.com/rcbops-cookbooks/swift-private-cloud.git"
            branches:
                master:
                    tags:
                        -v4.2.0
        chef_server:
            roles: []
        controller:
            roles: ['role[spc-starter-controller]']
        proxy:
            roles: ['role[spc-starter-proxy]']
        storage:
            roles: ['role[spc-starter-storage]']

tests:
  default:
    - compute
    - identity
  ha:
    - compute
    - identity
  glance-cf:
    - compute/images
    - image
  glance-local:
    - compute/images
    - image
  keystone-ldap:
    - compute/admin
    - compute/security_groups
    - compute/test_authorization.py
    - identity
  keystone-mysql:
    - compute/admin
    - compute/security_groups
    - compute/test_authorization.py
    - identity
  neutron:
    - network
  cinder-local:
    - compute/volumes
    - volume
  swift:
    - object_storage